Issue 1 setup scala project for cli
nervosum/nervosum pull request #5
Opened 2020-10-09 12:54 UTC by ruurtjan

This adds a some scaffolding for the CLI, without implementing any logic.

Closes #1

2020-10-09 15:12 UTC, bbroeksema requested changes
Looks good! Was much easier to get that up-and-running than I expected :D.

Let's make this a mono-repo project from the start by adding an sbt file at the root level, where version information and organization information will be shared among modules.

2020-10-09 15:12 UTC, bbroeksema commented on cli/build.sbt
> +
Shall we at least include some basic org/module information?
```
organization := "ai.nervosum"
organizationHomepage := Some(url("https://github.com/orgs/nervosum"))
```

See also my earlier remark about a top-level sbt file.

2020-10-09 15:12 UTC, bbroeksema commented on cli/src/main/scala/Main.scala
> +    version("Nervosum CLI 0.0.1")
Can we retrieve this from somewhere in stead of hardcoding? Preferably injected with `sbt`.

2020-10-09 15:12 UTC, bbroeksema commented on cli/README.md
> +This will create a binary called `target/scala-2.11/cli-out`.
Can we get rid of the `-out` extension and rename the binary to `nervosum`?

2020-10-09 15:12 UTC, bbroeksema commented on cli/.scalafmt.conf
> +maxColumn = 100
I would prefer this to move to the root directory. And I would also opt for a top-level `build.sbt` using sbt's module system. This makes sure we instill the mono-repo mindset from the very beginning.

2020-10-10 12:27 UTC, ruurtjan commented on cli/README.md
> +This will create a binary called `target/scala-2.11/cli-out`.
I don't think so. Let's rename the file before publishing it as part of #9.
This should do the trick for now:
```bash
ln -s /Users/ruurtjan/workspace/nervosum/nervosum/cli/target/scala-2.11/cli-out /usr/local/bin/nervosum
```

2020-10-16 08:46 UTC, ruurtjan commented on cli/build.sbt
> +
I've pushed a commit that moves adds this and sets up an sbt multi module project.

2020-10-16 08:47 UTC, ruurtjan commented on cli/src/main/scala/Main.scala
> +    version("Nervosum CLI 0.0.1")
Jep, the updates PR now uses a plugin to determine the version based on an SBT setting and git tags.

2020-10-16 08:47 UTC, ruurtjan commented on cli/.scalafmt.conf
> +maxColumn = 100
Moved :)

2020-10-16 08:52 UTC, bbroeksema commented on build.sbt
> +    com.typesafe.sbt.SbtGit.git.baseVersion := "0.0.1", // Upcoming version. See `README.md`
Awesome!

2020-10-16 08:55 UTC, bbroeksema approved these changes
Awesome. Let's move on!

2020-10-16 10:02 UTC, GuidoTournois approved these changes
All good!

2020-10-16 10:06 UTC, bbroeksema approved these changes

2020-10-16 10:24 UTC, merged